# x-liflow-app: &liflow-app
#   build:
#     context: .
#     dockerfile: Dockerfile
#   image: liflow-backend-image
#   pull_policy: never
#   env_file:
#     - .env.prod
#   restart: unless-stopped
#   networks:
#     - liflow-network-microservice

# x-liflow-shared-env: &liflow-shared-env
#   RABBITMQ_URL: amqp://${RABBITMQ_DEFAULT_USER:-guest}:${RABBITMQ_DEFAULT_PASS:-guest}@rabbitmq:5672
#   REDIS_HOST: redis

services:
  # api-gateway:
  #   <<: *liflow-app
  #   container_name: api-gateway-microservice
  #   environment:
  #     <<: *liflow-shared-env
  #     API_GATEWAY_DATABASE_HOST: api-gateway-postgres
  #     API_GATEWAY_DATABASE_URL: postgresql://${API_GATEWAY_DATABASE_USERNAME:-postgres}:${API_GATEWAY_DATABASE_PASSWORD:-123456}@api-gateway-postgres:5432/${API_GATEWAY_DATABASE_NAME:-postgres}?schema=${API_GATEWAY_DATABASE_SCHEMA:-public}
  #     IDENTITY_SERVICE_GRPC_URL: identity-service:${IDENTITY_SERVICE_GRPC_PORT:-50052}
  #     CHAT_SERVICE_GRPC_URL: chat-service:${CHAT_SERVICE_GRPC_PORT:-50055}
  #   ports:
  #     - "${API_GATEWAY_PORT:-3500}:${API_GATEWAY_PORT:-3500}"
  #     - "${API_GATEWAY_GRPC_PORT:-50051}:${API_GATEWAY_GRPC_PORT:-50051}"
  #   depends_on:
  #     api-gateway-postgres:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started
  #   command: node dist/apps/api-gateway/apps/api-gateway/src/main.js

  # identity-service:
  #   <<: *liflow-app
  #   container_name: identity-service-microservice
  #   environment:
  #     <<: *liflow-shared-env
  #     IDENTITY_SERVICE_DATABASE_HOST: identity-postgres
  #     IDENTITY_SERVICE_DATABASE_URL: postgresql://${IDENTITY_SERVICE_DATABASE_USERNAME:-postgres}:${IDENTITY_SERVICE_DATABASE_PASSWORD:-123456}@identity-postgres:5432/${IDENTITY_SERVICE_DATABASE_NAME:-postgres}?schema=${IDENTITY_SERVICE_DATABASE_SCHEMA:-public}
  #   ports:
  #     - "${IDENTITY_SERVICE_PORT:-3501}:${IDENTITY_SERVICE_PORT:-3501}"
  #     - "${IDENTITY_SERVICE_GRPC_PORT:-50052}:${IDENTITY_SERVICE_GRPC_PORT:-50052}"
  #   depends_on:
  #     identity-postgres:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started
  #   command: node dist/apps/identity-service/apps/identity-service/src/main.js

  # loyalty-service:
  #   <<: *liflow-app
  #   container_name: loyalty-service-microservice
  #   environment:
  #     <<: *liflow-shared-env
  #     LOYALTY_SERVICE_DATABASE_HOST: loyalty-postgres
  #     LOYALTY_SERVICE_DATABASE_URL: postgresql://${LOYALTY_SERVICE_DATABASE_USERNAME:-postgres}:${LOYALTY_SERVICE_DATABASE_PASSWORD:-123456}@loyalty-postgres:5432/${LOYALTY_SERVICE_DATABASE_NAME:-postgres}?schema=${LOYALTY_SERVICE_DATABASE_SCHEMA:-public}
  #   ports:
  #     - "${LOYALTY_SERVICE_PORT:-3502}:${LOYALTY_SERVICE_PORT:-3502}"
  #     - "${LOYALTY_SERVICE_GRPC_PORT:-50053}:${LOYALTY_SERVICE_GRPC_PORT:-50053}"
  #   depends_on:
  #     loyalty-postgres:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started
  #   command: node dist/apps/loyalty-service/apps/loyalty-service/src/main.js

  # nutrition-service:
  #   <<: *liflow-app
  #   container_name: nutrition-service-microservice
  #   environment:
  #     <<: *liflow-shared-env
  #     NUTRITION_SERVICE_DATABASE_HOST: nutrition-postgres
  #     NUTRITION_SERVICE_DATABASE_URL: postgresql://${NUTRITION_SERVICE_DATABASE_USERNAME:-postgres}:${NUTRITION_SERVICE_DATABASE_PASSWORD:-123456}@nutrition-postgres:5432/${NUTRITION_SERVICE_DATABASE_NAME:-postgres}?schema=${NUTRITION_SERVICE_DATABASE_SCHEMA:-public}
  #     NUTRITION_DATABASE_HOST: nutrition-postgres
  #     NUTRITION_DATABASE_URL: postgresql://${NUTRITION_SERVICE_DATABASE_USERNAME:-postgres}:${NUTRITION_SERVICE_DATABASE_PASSWORD:-123456}@nutrition-postgres:5432/${NUTRITION_SERVICE_DATABASE_NAME:-postgres}?schema=${NUTRITION_SERVICE_DATABASE_SCHEMA:-public}
  #   ports:
  #     - "${NUTRITION_SERVICE_PORT:-3503}:${NUTRITION_SERVICE_PORT:-3503}"
  #     - "${NUTRITION_SERVICE_GRPC_PORT:-50054}:${NUTRITION_SERVICE_GRPC_PORT:-50054}"
  #   depends_on:
  #     nutrition-postgres:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started
  #   command: node dist/apps/nutrition-service/apps/nutrition-service/src/main.js

  # chat-service:
  #   <<: *liflow-app
  #   container_name: chat-service-microservice
  #   environment:
  #     <<: *liflow-shared-env
  #     CHAT_SERVICE_DATABASE_HOST: chat-postgres
  #     CHAT_SERVICE_DATABASE_URL: postgresql://${CHAT_SERVICE_DATABASE_USERNAME:-postgres}:${CHAT_SERVICE_DATABASE_PASSWORD:-123456}@chat-postgres:5432/${CHAT_SERVICE_DATABASE_NAME:-postgres}?schema=${CHAT_SERVICE_DATABASE_SCHEMA:-public}
  #   ports:
  #     - "${CHAT_SERVICE_PORT:-3504}:${CHAT_SERVICE_PORT:-3504}"
  #     - "${CHAT_SERVICE_GRPC_PORT:-50055}:${CHAT_SERVICE_GRPC_PORT:-50055}"
  #   depends_on:
  #     chat-postgres:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started
  #   command: node dist/apps/chat-service/apps/chat-service/src/main.js

  # notification-service:
  #   <<: *liflow-app
  #   container_name: notification-service-microservice
  #   environment:
  #     <<: *liflow-shared-env
  #     NOTIFICATION_SERVICE_DATABASE_HOST: notification-postgres
  #     NOTIFICATION_SERVICE_DATABASE_URL: postgresql://${NOTIFICATION_SERVICE_DATABASE_USERNAME:-postgres}:${NOTIFICATION_SERVICE_DATABASE_PASSWORD:-123456}@notification-postgres:5432/${NOTIFICATION_SERVICE_DATABASE_NAME:-postgres}?schema=${NOTIFICATION_SERVICE_DATABASE_SCHEMA:-public}
  #   ports:
  #     - "${NOTIFICATION_SERVICE_PORT:-3505}:${NOTIFICATION_SERVICE_PORT:-3505}"
  #     - "${NOTIFICATION_SERVICE_GRPC_PORT:-50056}:${NOTIFICATION_SERVICE_GRPC_PORT:-50056}"
  #   depends_on:
  #     notification-postgres:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started
  #   command: node dist/apps/notification-service/apps/notification-service/src/main.js

  api-gateway-postgres:
    image: postgres:17-alpine
    container_name: api-gateway-postgres-microservice
    env_file:
      - .env.prod
    environment:
      # IMPORTANT:
      # - `${...}` here is resolved by Docker Compose *before* containers start.
      # - `env_file` does NOT populate those `${...}` values for Compose interpolation.
      #   (it only injects env into the container once it starts).
      # So we provide defaults to prevent Postgres from exiting when variables are missing.
      POSTGRES_USER: ${API_GATEWAY_DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${API_GATEWAY_DATABASE_PASSWORD:-123456}
      POSTGRES_DB: ${API_GATEWAY_DATABASE_NAME:-postgres}
    volumes:
      - api_gateway_postgres_data_microservice:/var/lib/postgresql/data
    ports:
      - "${API_GATEWAY_DATABASE_PORT:-5433}:5432"
    networks:
      - liflow-network-microservice
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  identity-postgres:
    image: postgres:17-alpine
    container_name: identity-postgres-microservice
    env_file:
      - .env.prod
    environment:
      POSTGRES_USER: ${IDENTITY_SERVICE_DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${IDENTITY_SERVICE_DATABASE_PASSWORD:-123456}
      POSTGRES_DB: ${IDENTITY_SERVICE_DATABASE_NAME:-postgres}
    volumes:
      - identity_postgres_data_microservice:/var/lib/postgresql/data
    ports:
      - "${IDENTITY_SERVICE_DATABASE_PORT:-5434}:5432"
    networks:
      - liflow-network-microservice
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  loyalty-postgres:
    image: postgres:17-alpine
    container_name: loyalty-postgres-microservice
    env_file:
      - .env.prod
    environment:
      POSTGRES_USER: ${LOYALTY_SERVICE_DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${LOYALTY_SERVICE_DATABASE_PASSWORD:-123456}
      POSTGRES_DB: ${LOYALTY_SERVICE_DATABASE_NAME:-postgres}
    volumes:
      - loyalty_postgres_data_microservice:/var/lib/postgresql/data
    ports:
      - "${LOYALTY_SERVICE_DATABASE_PORT:-5435}:5432"
    networks:
      - liflow-network-microservice
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      
  nutrition-postgres:
    image: postgres:17-alpine
    container_name: nutrition-postgres-microservice
    env_file:
      - .env.prod
    environment:
      POSTGRES_USER: ${NUTRITION_SERVICE_DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${NUTRITION_SERVICE_DATABASE_PASSWORD:-123456}
      POSTGRES_DB: ${NUTRITION_SERVICE_DATABASE_NAME:-postgres}
    volumes:
      - nutrition_postgres_data_microservice:/var/lib/postgresql/data
    ports:
      - "${NUTRITION_SERVICE_DATABASE_PORT:-5436}:5432"
    networks:
      - liflow-network-microservice
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  chat-postgres:
    image: postgres:17-alpine
    container_name: chat-postgres-microservice
    env_file:
      - .env.prod
    environment:
      POSTGRES_USER: ${CHAT_SERVICE_DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${CHAT_SERVICE_DATABASE_PASSWORD:-123456}
      POSTGRES_DB: ${CHAT_SERVICE_DATABASE_NAME:-postgres}
    volumes:
      - chat_postgres_data_microservice:/var/lib/postgresql/data
    ports:
      - "${CHAT_SERVICE_DATABASE_PORT:-5437}:5432"
    networks:
      - liflow-network-microservice
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  notification-postgres:
    image: postgres:17-alpine
    container_name: notification-postgres-microservice
    env_file:
      - .env.prod
    environment:
      POSTGRES_USER: ${NOTIFICATION_SERVICE_DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${NOTIFICATION_SERVICE_DATABASE_PASSWORD:-123456}
      POSTGRES_DB: ${NOTIFICATION_SERVICE_DATABASE_NAME:-postgres}
    volumes:
      - notification_postgres_data_microservice:/var/lib/postgresql/data
    ports:
      - "${NOTIFICATION_SERVICE_DATABASE_PORT:-5438}:5432"
    networks:
      - liflow-network-microservice
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      
  
  redis: 
    image: redis:7-alpine
    container_name: redis-microservice
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data_microservice:/data
    networks:
      - liflow-network-microservice
    # Ubuntu/EC2 optimizations
    # sysctls:
    #   - net.core.somaxconn=65535
    # ulimits:
    #   memlock: -1
    # environment:
    #   - REDIS_REPLICATION_MODE=master

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-microservice
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    volumes:
      - rabbitmq_data_microservice:/var/lib/rabbitmq
    networks:
      - liflow-network-microservice
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter-microservice
    ports:
      - "9100:9100"
    restart: unless-stopped
    networks:
      - liflow-network-microservice
    pid: host                          # Xem processes của host
    volumes:
      - /proc:/host/proc:ro            # CPU, RAM, processes
      - /sys:/host/sys:ro              # Hardware info
      - /:/rootfs:ro                   # Filesystem
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-microservice
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - prometheus_data_microservice:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - liflow-network-microservice

  loki:
    image: grafana/loki:3.4.2
    container_name: loki-microservice
    ports:
      - "3100:3100"
    restart: unless-stopped
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
      - loki_data_microservice:/loki
    command: -config.file=/etc/loki/local-config.yml
    networks:
      - liflow-network-microservice
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana-microservice
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data_microservice:/var/lib/grafana
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    networks:
      - liflow-network-microservice

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight-microservice
    ports:
      - "5540:5540" 
    restart: unless-stopped
    volumes:
      - redisinsight_data_microservice:/data
    networks:
      - liflow-network-microservice
      
  backup-api-gateway:
    image: prodrigestivill/postgres-backup-local
    container_name: backup-api-gateway-microservice
    env_file:
      - .env.prod
    restart: unless-stopped
    volumes:
      - backup_api_gateway_data_microservice:/backups
    environment:
      - POSTGRES_HOST=api-gateway-postgres
      - POSTGRES_DB=${API_GATEWAY_DATABASE_NAME:-postgres}
      - POSTGRES_USER=${POSTGRES_BACKUP_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_BACKUP_USER_PASSWORD:-123456}
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - EXTRA_OPTS=--schema=public
    depends_on:
      api-gateway-postgres:
        condition: service_healthy
    networks:
      - liflow-network-microservice

  backup-identity:
    image: prodrigestivill/postgres-backup-local
    container_name: backup-identity-microservice
    env_file:
      - .env.prod
    restart: unless-stopped
    volumes:
      - backup_identity_data_microservice:/backups
    environment:
      - POSTGRES_HOST=identity-postgres
      - POSTGRES_DB=${IDENTITY_SERVICE_DATABASE_NAME:-postgres}
      - POSTGRES_USER=${POSTGRES_BACKUP_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_BACKUP_USER_PASSWORD:-123456}
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - EXTRA_OPTS=--schema=public
    depends_on:
      identity-postgres:
        condition: service_healthy
    networks:
      - liflow-network-microservice

  backup-loyalty:
    image: prodrigestivill/postgres-backup-local
    container_name: backup-loyalty-microservice
    env_file:
      - .env.prod
    restart: unless-stopped
    volumes:
      - backup_loyalty_data_microservice:/backups
    environment:
      - POSTGRES_HOST=loyalty-postgres
      - POSTGRES_DB=${LOYALTY_SERVICE_DATABASE_NAME:-postgres}
      - POSTGRES_USER=${POSTGRES_BACKUP_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_BACKUP_USER_PASSWORD:-123456}
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - EXTRA_OPTS=--schema=public
    depends_on:
      loyalty-postgres:
        condition: service_healthy
    networks:
      - liflow-network-microservice
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch-microservice
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data_microservice:/usr/share/elasticsearch/data
    restart: unless-stopped
    networks:
      - liflow-network-microservice
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana-microservice
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - kibana_data_microservice:/usr/share/kibana/data
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - liflow-network-microservice
    
  # es-sync:
  #   build:
  #     context: .
  #     dockerfile: es-sync.Dockerfile
  #   image: es-sync-image
  #   pull_policy: build
  #   container_name: es-sync
  #   volumes:
  #     - ./scripts:/app/scripts
  #   entrypoint: ["sh", "/app/scripts/seed-if-empty.sh"]
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:123456@postgres:5432/postgres?schema=public

  #   depends_on:
  #     postgres:
  #         condition: service_healthy
  #     elasticsearch:
  #         condition: service_healthy
  #   restart: "no" 
  #   networks:
  #     - liflow-network

networks:
  liflow-network-microservice:
    driver: bridge

volumes:
  api_gateway_postgres_data_microservice:
  identity_postgres_data_microservice:
  loyalty_postgres_data_microservice:
  nutrition_postgres_data_microservice:
  redis_data_microservice:
  prometheus_data_microservice:
  grafana_data_microservice:
  redisinsight_data_microservice:
  backup_api_gateway_data_microservice:
  backup_identity_data_microservice:
  backup_loyalty_data_microservice:
  elasticsearch_data_microservice:
  kibana_data_microservice:
  loki_data_microservice:
  rabbitmq_data_microservice:
  chat_postgres_data_microservice:
  notification_postgres_data_microservice:
